### PR TITLE
Update UI

### PR DESCRIPTION
**Pull request by othnielussher**
Changes made:

1. Close dialog after user clicks on copy code. This way they can see the toast and it's content
2. Add a change notifier for storing the search query, resulting in the removal of some functions and variables
3. Fix white line below search bar
4. Fix search bar text alignment
5. Update certain parts of the UI (including the ShowCaseContent and the side bar, and the NavBar widget)

### CODE REVIEW

**Comment by dhruvpatidar359** [comment]
thanks @othnielussher  i will review it

**Comment by dhruvpatidar359** [comment]
@othnielussher  Hi , The UI looks good , but there are two problems 
1 ) The search is not working properly ( You can see in the video)

https://github.com/dhruvpatidar359/Fluttersnips/assets/103873587/1171c1d5-9b8b-4519-8025-1f7deb79d8e5


2 ) After login , onpress on the profile is not working , user will not able to see the contribution count and logout.

may you please try to fix these .

Thanks for the contribution ♥

**Comment by othnielussher** [comment]
> @othnielussher  Hi , The UI looks good , but there are two problems 
> 
> 1 ) The search is not working properly ( You can see in the video)
> 
> 
> 
> https://github.com/dhruvpatidar359/Fluttersnips/assets/103873587/1171c1d5-9b8b-4519-8025-1f7deb79d8e5
> 
> 
> 
> 
> 
> 2 ) After login , onpress on the profile is not working , user will not able to see the contribution count and logout.
> 
> 
> 
> may you please try to fix these .
> 
> 
> 
> Thanks for the contribution ♥

Yes sure. I'll take a look at it

**Comment by dhruvpatidar359** [comment]
I checked the login problem that is now gone , that was due the use of a package called as image network , so by setting the CORS config , i shifted it to the NetworkImage and now it is working . The only thing that is not working is search now .

Have a look 

https://github.com/dhruvpatidar359/Fluttersnips/assets/103873587/d388f6ab-97e6-47f6-84d9-3f97c11dcd14

you just have to replace the ImageNetwork with NetworkImage in the logginDialog() and loggedinProfile and it will work

Check this 
image


this one also 
image

**Pull request closed without merging**
